### ISSUE TITLE
tarea practica de conversiones 

### ISSUE THREAD

**Issue by saul19bautista** [SistemasTecTlaxiaco/ejercicios-equipo-saul-lopez-bautista#2]
[Uploading practica sobre converciones Saul Lopez Bautista.pdf…]()

**Comment by 71santiago7** [comment]
[Uploading PRACTICA_DE_EQUIPO_RENE SANTIAGO.pdf…]()

**Comment by 7177981** [comment]
[practica sobre converciones Saul Lopez Bautista.pdf](https://github.com/SistemasTecTlaxiaco/ejercicios-equipo-saul-lopez-bautista/files/7223486/practica.sobre.converciones.Saul.Lopez.Bautista.pdf)

**Comment by josealfredo79** [comment]
Falta la calificación de acuerdo a la rúbrica

**Comment by josealfredo79** [comment]
Falta calificacion

**Comment by irving1613** [comment]
Trabajo bien estructurado y desarrollado de manerea correcta.
**Calificacion: 20**

**Comment by ErickRamos99** [comment]
> [PRACTICA_DE_EQUIPO SAMUEL HOYOS MORA.pdf](https://github.com/SistemasTecTlaxiaco/ejercicios-equipo-saul-lopez-bautista/files/7208209/PRACTICA_DE_EQUIPO.SAMUEL.HOYOS.MORA.pdf)

20%/20%
Un excelente trabajo todo esta muy bien.

**Comment by gilbertovelasco1** [comment]
excelente trabajo 

calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
